### ISSUE TITLE
BridgedbManager.loadRelationalDatabase with Scyjava does not work

### ISSUE THREAD

**Issue by kozo2** [egonw/bacting#57] opened 2021-08-31 18:21 UTC
## Bacting API method with unexpected output

loadRelationalDatabase did not work when importing BridgedbManager with scyjava.

See 
![image](https://user-images.githubusercontent.com/12192/131555423-8b52c359-3058-43c9-98f2-b39e2642ac35.png)

### Expected Output

```
test will be IDMapper object
```

### Actual Output

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-eee82142c20a> in <module>()
----> 1 test = bdbClass.loadRelationalDatabase("./metabolites_20210109.bridge")

TypeError: No matching overloads found for *static* net.bioclipse.managers.BridgedbManager.loadRelationalDatabase(str), options are:
	public org.bridgedb.IDMapper net.bioclipse.managers.BridgedbManager.loadRelationalDatabase(java.lang.String) throws net.bioclipse.core.business.BioclipseException

```

## Additional context

You can reproduce this with https://colab.research.google.com/drive/1hs-yuKl_pOCIkUl5DM4h_Ecyp6rI2cOx?usp=sharing

**Comment by egonw** [comment] 2021-09-13 18:03
@kozo2, sorry for the delay... could I ask you to try the following?

```python
test = bdbClass.loadRelationalDatabase(to_java("./metabolites_20210109.bridge"))
```

Looking at the error message, I think it's trying to pass a Python `str` to the method, see also https://github.com/scijava/scyjava#available-functions

**Comment by kozo2** [comment] 2021-09-13 21:04
@egonw I updated https://colab.research.google.com/drive/1hs-yuKl_pOCIkUl5DM4h_Ecyp6rI2cOx?usp=sharing
It tries
```
import scyjava
test = bdbClass.loadRelationalDatabase(scyjava.to_java("./metabolites_20210109.bridge"))
```
but, there is still the following TypeError
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-3d6a271882bf> in <module>()
----> 1 test = bdbClass.loadRelationalDatabase(scyjava.to_java("./metabolites_20210109.bridge"))
      2 #test = bdbClass.loadRelationalDatabase("./metabolites_20210109.bridge")

TypeError: No matching overloads found for *static* net.bioclipse.managers.BridgedbManager.loadRelationalDatabase(java.lang.String), options are:
	public org.bridgedb.IDMapper net.bioclipse.managers.BridgedbManager.loadRelationalDatabase(java.lang.String) throws net.bioclipse.core.business.BioclipseException
```
![image](https://user-images.githubusercontent.com/12192/133156166-3337e559-9b3c-46a3-af78-32449199c888.png)

**Comment by egonw** [comment] 2021-09-14 05:04
I got some time to look into the notebook more... there was at least a step missing... the `bdbClass` should not be used in a static way, but be instantiated around an "Eclipse workspace":

```python
workspaceRoot = "."
bdbClass = jimport("net.bioclipse.managers.BridgedbManager")
bdb = bdbClass(workspaceRoot)
```

Then, put the BridgeDb database in a project (which will go into that workspace):

```python
!mkdir -p BridgeDb; cd BridgeDb; wget https://ndownloader.figshare.com/files/26001794
!cp 26001794 metabolites_20210109.bridge
```

Then, the loading would be like this:

```python
test = bdb.loadRelationalDatabase("/BridgeDb/metabolites_20210109.bridge")
```

But then I still run into a problem, a missing class. I will look into that next.

**Comment by egonw** [comment] 2021-09-14 05:10
I can confirm this dependency is indeed not given. Fixing this now.

**Comment by egonw** [comment] 2021-09-14 05:19
Okay, the method actually doesn't use the workspace approach :/

So, this is the code that works for me now:

I got some time to look into the notebook more... there was at least a step missing... the `bdbClass` should not be used in a static way, but be instantiated around an "Eclipse workspace":

```python
from scyjava import config, jimport

config.add_endpoints('io.github.egonw.bacting:managers-bridgedb:0.0.23-SNAPSHOT')

workspaceRoot = "."
bdbClass = jimport("net.bioclipse.managers.BridgedbManager")
bdb = bdbClass(workspaceRoot)

test = bdb.loadRelationalDatabase("./Test/complexes_20200510.bridge")
```

I will try to release 0.0.23 today.

**Comment by egonw** [comment] 2021-09-14 05:21
Fixed in https://github.com/egonw/bacting/commit/08a23fbea780b23a34f2ff13d09130f34b0f41b5

**Closed by egonw** 2021-09-14 05:21 UTC
Labels: bug

**Comment by egonw** [comment] 2021-09-14 11:02
Bacting 0.0.23 is released which includes this fix.

**Comment by kozo2** [comment] 2021-09-14 15:03
@egonw Thanks. I updated https://colab.research.google.com/drive/1hs-yuKl_pOCIkUl5DM4h_Ecyp6rI2cOx?usp=sharing .
It works well.
